---
title: "Maturation States of all the unc strains"
output: html_notebook
---
```{r}
#libraries used in this notebook
library(gmodels)
library(ggplot2)
library(qqplotr)
library(dplyr)
library(tidyverse)
library(ggpubr)
library(here)
#reads in the dataframe
dat <-read.csv(here("datafolder", "AV_AL_data_uncs.csv"))
factorNames <- c("control","unc-104(e1265)", "unc-33(mn407)", "unc-33(e204)", "unc-44(hrt-2)") #defines the genotypes to be analyzed 
unc_mat_dat <- filter(dat, genotype %in% factorNames) #filters only the factors (genotypes) to be analyzed
unc_mat_dat <- filter(unc_mat_dat, temperature == 20)
unc_mat_dat$genotype <- factor(unc_mat_dat$genotype, levels =c("control","unc-104(e1265)", "unc-33(mn407)", "unc-33(e204)", "unc-44(hrt-2)"))#reorders the levels to the way that I want them to appear on the graphs ahead

```

The data is properly filtered and ordered for the genotypes that we want. Our library is loaded

Now we have to manipulate the dataframe so that we can have two different dataframes. One will contain the red data and the other will contain the yellow. 

```{r}
#organization of the data
#subset the columns that will be used in analysis and renames columns to more readable names
unc_mat_dat_red <- select(unc_mat_dat,id, genotype, neurite_red, soma_red, cell_red)

unc_mat_dat_red
unc_mat_dat_red <- unc_mat_dat_red %>% 
  rename(Neurite = neurite_red,
         Soma = soma_red,
         Cell = cell_red
    )
unc_mat_dat_red
#now for the yellow data
unc_mat_dat_yellow <- select(unc_mat_dat, id, genotype, neurite_yellow, soma_yellow, cell_yellow)
unc_mat_dat_yellow <-unc_mat_dat_yellow %>% 
  rename(Neurite = neurite_yellow,
         Soma = soma_yellow,
         Cell = cell_yellow
    )
#pivots the location data for the observations longer. Stores the data values under values column and the old column names under a new column named location.
unc_mat_dat_red <-unc_mat_dat_red %>%
 pivot_longer(cols = c(Neurite, Soma, Cell),
   names_to = "location",
   values_to = "value")
unc_mat_dat_yellow <-unc_mat_dat_yellow %>%
 pivot_longer(cols = c(Neurite, Soma, Cell),
   names_to = "location",
   values_to = "value")
#reorders the location factors to aide in graphical representation of data
unc_mat_dat_red$location <- factor(unc_mat_dat_red$location,
                                    levels = c("Neurite", "Soma", "Cell"))

unc_mat_dat_yellow$location <- factor(unc_mat_dat_yellow$location,
                                    levels = c("Neurite", "Soma", "Cell"))

```
The data are now organized into two different dataframes. They are now ready to be visualized. 

```{r}
library(ggtext)
#jitter and theme elements to feed into ggplots
fig_one_theme <- theme(axis.text.x = element_markdown(face = "italic", size = 13),
                       axis.title.x = element_blank(),
                       axis.ticks.x = element_blank(),
                       panel.background = element_blank(),
                       panel.grid.major.x = element_line(color = "snow3"),
                       panel.grid = element_line(linetype = "solid", color = "snow3"),
                       panel.border = element_rect(linetype = "solid", fill = NA),
                       text = element_text(size = 24),
) #this will need to be resized later, maybe like to 18 or so

#position jitter function
posn_j <- position_jitter(width=.2)

#dot plot of the red data in the locations of the neuron faceted
unc_mat_plot_red <- ggplot(data=unc_mat_dat_red, aes(x=genotype, y=value, fill=location)) +
  geom_violin(aes(x=genotype, y=value, fill=location),
              fill = "red",
              alpha = .3,
              draw_quantiles = c(.5))+
  facet_wrap(vars(location))+ #facets the data to show the location in the cell of the red AG's
  geom_point(alpha = 0.6,
             position =posn_j)+ #creates a dotplot of the data
  stat_summary(fun.data=mean_sdl, fun.args = list(mult=1), 
        geom="errorbar", color="red", alpha = .8,  width=0.2, size = .8) + #creates an error bar based on one standard devation of the data
  fig_one_theme+ #loads theme elements from other figures in the manuscript
  coord_cartesian(ylim = c(0,18))+ #creates the limits of the graph
  theme(legend.position = "none")+ #gets rid of legend
  labs(y = "ALs per AIY Neuron")
  #geom_signif(stat="identity"
              #data = data.frame(x=c(.85,.85),
                               # xend=c(2.15,3.15),
                               # y=c(13,15),
                                #annotation=c(""))
              

unc_mat_plot_red

#dot plot of the yellow data in the locations of the neuron faceted
unc_mat_plot_yellow <- ggplot(data=unc_mat_dat_yellow, aes(x=genotype, y=value, fill=location)) +
  geom_violin(aes(x=genotype, y=value, fill=location),
              fill = "yellow",
              alpha = .3,
              draw_quantiles = c(.5))+
  facet_wrap(vars(location))+ #facets the data to show the location in the cell of the red AG's
  geom_point(alpha = 0.6,
             position =posn_j)+ #creates a dotplot of the data
  stat_summary(fun.data=mean_sdl, fun.args = list(mult=1), 
        geom="errorbar", color="red", alpha = .8,  width=0.2, size = .8) + #creates an error bar based on one standard devation of the data
  fig_one_theme+ #loads theme elements from other figures in the manuscript
  coord_cartesian(ylim = c(0,18))+ #creates the limits of the graph
  theme(legend.position = "none")+
  labs(y = "AGs per AIY Neuron")


unc_mat_plot_yellow

```

