---
title: "unc-104_vs_control_plot"
output: html_notebook
---


```{r}
#packages
library(dplyr)
library(ggplot2)
library(here)
library(tidyr)
library(ggsignif)
#reads in the dataframe
dat <-read.csv(here("datafolder", "unc-104_data.csv")) #reads in csv data file
here()
factorNames <- c("control", "unc-104(e1265)") #defines the genotypes to be analyzed 
traf_dat <- filter(dat, genotype %in% factorNames) #filters only the factors (genotypes) to be analyzed
traf_dat$genotype <- factor(traf_dat$genotype, levels =c("control", "unc-104(e1265)"))

```

```{r}
#organization of the data
#subset the columns that will be used in analysis and renames columns to more readable names
traf_dat <- select(traf_dat,id, genotype, neurite_total, soma_total, cell_total)

traf_dat
traf_dat <- traf_dat %>% 
  rename(Neurite = neurite_total,
         Soma = soma_total,
         Cell = cell_total
    )
traf_dat


```

```{r}
#statistical tests for significance Neurite
#independent t-test
#checking t-test assumptions
unc_104_one_way <-lm(Neurite ~ genotype, data= traf_dat)#creates a linear model of data to be analyzed 
plot(unc_104_one_way) #creates plots to visually analyze data
aov_residuals <- resid(unc_104_one_way) #extracts residuals from linear model
shapiro.test(x = aov_residuals)#tests for normality of residuals in data set. if significant, data are non-normal.  significant shapiro test -> use fligner  
bartlett.test(data = traf_dat , Neurite ~ genotype )#test for homogeneity of variance (if p is significant variance is unequal  amoung groups), Bartlett test assumes normality.
fligner.test(Neurite ~ genotype, data = traf_dat) # a nonparametric test for homogeneity of variance to be used when data are non-normal
#statistical tests are now ready to be run below
t.test(Neurite ~ genotype, data=traf_dat, var.equal=TRUE) #if nonparametric, use the Mann-whitney (aka wilcox rank sum test)
wilcox.test(Neurite ~ genotype, data=traf_dat, na.rm=FALSE, paired=FALSE, conf.int=TRUE)

```

```{r}
#statistical tests for significance Soma
#independent t-test
#checking t-test assumptions
unc_104_one_way <-lm(Soma ~ genotype, data= traf_dat)#creates a linear model of data to be analyzed 
plot(unc_104_one_way) #creates plots to visually analyze data
aov_residuals <- resid(unc_104_one_way) #extracts residuals from linear model
shapiro.test(x = aov_residuals)#tests for normality of residuals in data set. if significant, data are non-normal.  significant shapiro test -> use fligner  
bartlett.test(data = traf_dat , Soma ~ genotype )#test for homogeneity of variance (if p is significant variance is unequal  amoung groups), Bartlett test assumes normality.
fligner.test(Soma ~ genotype, data = traf_dat) # a nonparametric test for homogeneity of variance to be used when data are non-normal
#statistical tests are now ready to be run below
t.test(Soma ~ genotype, data=traf_dat, var.equal=TRUE) #if nonparametric, use the Mann-whitney (aka wilcox rank sum test)
wilcox.test(Soma ~ genotype, data=traf_dat, na.rm=FALSE, paired=FALSE, conf.int=TRUE)
```

```{r}
#statistical tests for significance Cell
#independent t-test
#checking t-test assumptions
unc_104_one_way <-lm(Cell ~ genotype, data= traf_dat)#creates a linear model of data to be analyzed 
plot(unc_104_one_way) #creates plots to visually analyze data
aov_residuals <- resid(unc_104_one_way) #extracts residuals from linear model
shapiro.test(x = aov_residuals)#tests for normality of residuals in data set. if significant, data are non-normal.  significant shapiro test -> use fligner  
bartlett.test(data = traf_dat , Cell ~ genotype )#test for homogeneity of variance (if p is significant variance is unequal  amoung groups), Bartlett test assumes normality.
fligner.test(Cell ~ genotype, data = traf_dat) # a nonparametric test for homogeneity of variance to be used when data are non-normal
#statistical tests are now ready to be run below
t.test(Cell ~ genotype, data=traf_dat, var.equal=TRUE) #if nonparametric, use the Mann-whitney (aka wilcox rank sum test)
wilcox.test(Cell ~ genotype, data=traf_dat, na.rm=FALSE, paired=FALSE, conf.int=TRUE)
```

```{r}
#neurite trafficking plot
fig_3_plotB <- ggplot(data=traf_dat, aes(x=genotype, y=Neurite)) +
  geom_violin(draw_quantiles = c(.5), fill = "snow2")+
  geom_point(alpha = 0.6,
             position =posn_j,)+
  stat_summary(fun.data=mean_sdl, fun.args = list(mult=1), 
        geom="errorbar", color="red", alpha = .8,  width=0.2, size = .8) +
  fig_one_theme+
  coord_cartesian(ylim = c(0,20))+
  labs(y = "AV's per AIY Neurite",
       x = "Genotype")
fig_3_plotB
```

```{r}
fig_3_plotC <- ggplot(data=traf_dat, aes(x=genotype, y=Soma)) +
  geom_violin(draw_quantiles = c(.5), fill = "snow2")+
  geom_point(alpha = 0.6,
             position =posn_j,)+
  stat_summary(fun.data=mean_sdl, fun.args = list(mult=1), 
        geom="errorbar", color="red", alpha = .8,  width=0.2, size = .8) +
  fig_one_theme+
  coord_cartesian(ylim = c(0,20))+
  labs(y = "AV's per AIY Soma",
       x = "Genotype")+
  geom_signif(comparisons = list(c("control", "unc-104(e1265)")),
              annotations = c("1.93e-03"))
fig_3_plotC
```

```{r}
fig_3_plotD <- ggplot(data=traf_dat, aes(x=genotype, y=Cell)) +
  geom_violin(draw_quantiles = c(.5), fill = "snow2")+
  geom_point(alpha = 0.6,
             position =posn_j,)+
  stat_summary(fun.data=mean_sdl, fun.args = list(mult=1), 
        geom="errorbar", color="red", alpha = .8,  width=0.2, size = .8) +
  fig_one_theme+
  coord_cartesian(ylim = c(0,20))+
  labs(y = "AV's per AIY Cell",
       x = "Genotype") +
  geom_signif(comparisons = list(c("control", "unc-104(e1265)")),
              annotations = c("6.43e-04"))
fig_3_plotB
fig_3_plotC
fig_3_plotD
```


